### ISSUE TITLE
Host rewrite

### ISSUE THREAD

**Issue by somehowchris** [felipenoris/hyper-reverse-proxy#18]
Hey :)

So I have been playing a bit around with this crate. Seems nice but some servers complain about SNI & Host header conflicts.

I couldn‘t see any code done to rewrite the host header. Did I miss something?

I‘m neither a go king but I think https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/net/http/httputil/reverseproxy.go;l=148 Is the part of go rewriting the host header

**Comment by somehowchris** [comment]
Don’t wanna push, but do you consider releasing this? @felipenoris

**Comment by felipenoris** [comment]
I'll tag a new release soon.
Thanks!
