### ISSUE TITLE
Update to lastest hyper

### ISSUE THREAD

**Issue by felipenoris** [felipenoris/hyper-reverse-proxy#4]
Can this be updated to the latest hyper?

Ref https://github.com/felipenoris/hyper-reverse-proxy/tree/fn/update

**Comment by brendanzab** [comment]
If you like I can give you this repository, along with the crate name! I haven't really been in the web dev space for a while now!

**Comment by felipenoris** [comment]
Yes! I would accept that.

**Comment by felipenoris** [comment]
Now that https://github.com/hyperium/hyper/commit/30870029b9eb162f566d8dddd007fb6df9cd69af was merged, I'm able to update this to the lastest hyper. There's a working example at https://github.com/felipenoris/reverse-proxies

**Comment by brendanzab** [comment]
Oh woops, sorry for forgetting about this - hooray for the disappearing github notifications! I can transfer it onto you if you're still interested - I thing the repo name needs to be free on your account first (you might have to rename your fork first).

**Comment by brendanzab** [comment]
Oh, looks like you've done it! :) https://github.com/felipenoris/tmp-hyper-reverse-proxy - just let me know and I'll go ahead.

**Comment by brendanzab** [comment]
Would be lovely to have somebody helping out on this kind of middleware for Rust's HTTP ecosystem - would have really helped me out a couple of years ago! 😄

**Comment by felipenoris** [comment]
Yes, go ahead with the transfer. Thanks!

**Comment by brendanzab** [comment]
Done! One we have it I'll give you crates.io access. You'll probably want to update links on the README and Cargo.toml as well. Thanks so much! 😄

**Comment by felipenoris** [comment]
Nothing happened here... Am I missing something?

**Comment by brendanzab** [comment]
I think you need to accept the transfer 🤔

**Comment by felipenoris** [comment]
Now I see... What happens is that github sends an email with a link. But now the link expired... Sorry about that.. Can you repeat the transfer?

**Comment by felipenoris** [comment]
It works! Thanks!

**Comment by brendanzab** [comment]
Yayy! Now head to crates.io - I've added you as an owner, but you'll have to accept it there too. Also, might be a good idea to update some of the links in the cargo manifest file, and the README, and set it up on Travis.
