### ISSUE TITLE
Support for hyper 0.13

### ISSUE THREAD

**Issue by mrusme** [felipenoris/hyper-reverse-proxy#8]
I've tried using this crate with the latest version of hyper (`0.13.4`) but unfortunately it turns out this doesn't work out of the box. Are there any plans for updating this repo to the latest hyper version? :-)

**Comment by jabdoa2** [comment]
I got those changes locally. Is this project still active? Are PRs welcome?

**Comment by mrusme** [comment]
@jabdoa2 it would be cool if you could try a PR. :) Let's see, maybe @felipenoris accepts it.

**Comment by jabdoa2** [comment]
Hope so. Let's wait for him to confirm as there are other stale PRs

**Comment by felipenoris** [comment]
yes, PRs are welcome

**Comment by jabdoa2** [comment]
Awesome. Will create one tomorrow.
